INSERT INTO CIRCUS (ID,ADDRESS,DESCR,FOUNDATION_DATE,HEAD_OF,NAME) VALUES (1,'94006, г. Воронеж, ул. 20-летия октября, 121','Воронежский государственный цирк им. А. Л. Дурова',NULL,NULL,'Воронежский цирк');

INSERT INTO CIRCUS_LAYOUTS (ID,CAPACITY,NAME,CIRCUS_ID) VALUES (1,2400,'Арена Воронежского цирка ',1);

INSERT INTO CIRCUS_SECTORS (ID,CAPACITY,DESCRIPTION,NAME,SIDE,LAYOUT_ID) VALUES (1,0,NULL,'Сектор 1',1,1);
INSERT INTO CIRCUS_SECTORS (ID,CAPACITY,DESCRIPTION,NAME,SIDE,LAYOUT_ID) VALUES (2,0,NULL,'Сектор 2',1,1);
INSERT INTO CIRCUS_SECTORS (ID,CAPACITY,DESCRIPTION,NAME,SIDE,LAYOUT_ID) VALUES (3,0,NULL,'Сектор 3',1,1);
INSERT INTO CIRCUS_SECTORS (ID,CAPACITY,DESCRIPTION,NAME,SIDE,LAYOUT_ID) VALUES (4,0,NULL,'Сектор 4',1,1);
INSERT INTO CIRCUS_SECTORS (ID,CAPACITY,DESCRIPTION,NAME,SIDE,LAYOUT_ID) VALUES (5,0,NULL,'Сектор 1',0,1);
INSERT INTO CIRCUS_SECTORS (ID,CAPACITY,DESCRIPTION,NAME,SIDE,LAYOUT_ID) VALUES (6,0,NULL,'Сектор 2',0,1);
INSERT INTO CIRCUS_SECTORS (ID,CAPACITY,DESCRIPTION,NAME,SIDE,LAYOUT_ID) VALUES (7,0,NULL,'Сектор 3',0,1);
INSERT INTO CIRCUS_SECTORS (ID,CAPACITY,DESCRIPTION,NAME,SIDE,LAYOUT_ID) VALUES (8,0,NULL,'Сектор 4',0,1);

INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (1,29,1,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (2,33,2,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (3,40,3,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (4,45,4,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (5,50,5,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (6,54,6,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (7,63,7,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (8,67,8,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (9,71,9,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (10,58,10,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (11,61,11,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (12,64,12,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (13,60,13,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (14,57,14,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (15,57,15,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (16,52,16,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (17,47,17,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (18,38,18,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (19,28,19,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (20,25,20,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (21,6,21,1,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (22,28,1,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (23,33,2,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (24,38,3,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (25,43,4,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (26,47,5,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (27,53,6,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (28,61,7,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (29,65,8,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (30,68,9,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (31,58,10,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (32,61,11,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (33,65,12,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (34,60,13,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (35,53,14,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (36,53,15,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (37,71,16,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (38,68,17,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (39,57,18,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (40,51,19,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (41,24,20,0,1);
INSERT INTO CIRCUS_ROWS (ID,CAPACITY,ROW_NUM,SIDE,LAYOUT_ID) VALUES (42,13,21,0,1);



INSERT INTO TROUPES (ID,HEAD_OF,NAME) VALUES (1,'Михалков','Канские Львы');
INSERT INTO TROUPES (ID,HEAD_OF,NAME) VALUES (2,'Шевченко','Цирк на воде');

INSERT INTO PROGRAMS (ID,DESCRIPTION,END_DATE,START_DATE,TITLE,TROUPE_ID) VALUES (1,'Незабываемое шоу',TO_DATE('2016-01-01 09:00:00','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2015-10-01 09:00:00','YYYY-MM-DD HH24:MI:SS'),'Цирк на воде в Воронеже',2);
INSERT INTO PROGRAMS (ID,DESCRIPTION,END_DATE,START_DATE,TITLE,TROUPE_ID) VALUES (2,NULL,TO_DATE('2016-05-01 09:00:00','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2016-02-01 09:00:00','YYYY-MM-DD HH24:MI:SS'),'Львы на арене',1);




