INSERT INTO CIRCUS (ID,ADDRESS,DESCR,FOUNDATION_DATE,HEAD_OF,NAME) VALUES (1,'94006, г. Воронеж, ул. 20-летия октября, 121','Воронежский государственный цирк им. А. Л. Дурова',NULL,NULL,'Воронежский цирк');

INSERT INTO CIRCUS_LAYOUTS (ID,CAPACITY,NAME,CIRCUS_ID) VALUES (1,2400,'Арена Воронежского цирка ',1);

INSERT INTO TROUPES (ID,HEAD_OF,NAME) VALUES (1,'Михалков','Канские Львы');
INSERT INTO TROUPES (ID,HEAD_OF,NAME) VALUES (2,'Шевченко','Цирк на воде');

INSERT INTO PROGRAMS (ID,DESCRIPTION,END_DATE,START_DATE,TITLE,TROUPE_ID) VALUES (1,'Незабываемое шоу',TO_DATE('2016-01-01 09:00:00','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2015-10-01 09:00:00','YYYY-MM-DD HH24:MI:SS'),'Цирк на воде в Воронеже',2);
INSERT INTO PROGRAMS (ID,DESCRIPTION,END_DATE,START_DATE,TITLE,TROUPE_ID) VALUES (2,NULL,TO_DATE('2016-05-01 09:00:00','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2016-02-01 09:00:00','YYYY-MM-DD HH24:MI:SS'),'Львы на арене',1);




